version: '2'

services:
  app:
    image: '${artifactId}:latest'
    build:
      context: .
    container_name: app
    ports:
      - "8000:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${artifactId}
      - SPRING_DATASOURCE_USERNAME=example
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=example
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=${artifactId}