# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build Archetype with Maven
        run: mvn -B -U clean install --file pom.xml
      - name: Create archetype
        run: |
          cd ..
          mvn archetype:generate -B -DarchetypeGroupId=com.example -DarchetypeArtifactId=dockerized-springboot-archetype -DarchetypeVersion=0.0.1-SNAPSHOT -DartifactId=archetype-test -DgroupId=com.example -Dversion=1.0-SNAPSHOT
      - name: Build application with Maven
        run: |
          cd ..
          cd archetype-test
          mvn -B install --file pom.xml

      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2

      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: target/site/jacoco/

      - name: OWASP Dependency checker
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        env:
          JAVA_HOME: /opt/jdk
        with:
          project: '${artifactId}'
          path: '.'
          format: 'HTML'
          args: >
            --enableRetired
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
          name: Dependency check report
          path: ${{github.workspace}}/reports
