# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build-archetype:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B -U clean install --file pom.xml


  build-application:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /home/runner/work/_temp/_github_workflow/

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Create archetype
        run: mvn archetype:generate -B -DarchetypeGroupId=com.example -DarchetypeArtifactId=dockerized-springboot-archetype -DarchetypeVersion=0.0.1-SNAPSHOT -DartifactId=archetype-test -DgroupId=com.example -Dversion=1.0-SNAPSHOT

      - name: Build with Maven
        run: mvn -B -U clean install --file pom.xml
        working-directory: /home/runner/work/_temp/_github_workflow/archetype-test

      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: /github/workflow/archetype-test/target/site/jacoco/jacoco.csv

      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@master
        with:
          name: Code coverage report
          path: /home/runner/work/_temp/_github_workflow/archetype-test/target/site/jacoco/

      - name: OWASP Dependency checker
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        env:
          JAVA_HOME: /opt/jdk
        with:
          project: 'Archetype test'
          path: '/github/workflow/archetype-test/'
          format: 'HTML'
          args: >
            --enableRetired
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
          name: Dependency check report
          path: ${{github.workspace}}/reports
